# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Templatizer < Formula
  desc ""
  homepage "https://github.com/wesovilabs/homebrew-tools"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wesovilabs/templatizer/releases/download/v0.0.1/templatizer_0.0.1_darwin_amd64.tar.gz"
      sha256 "2ea49bdcd01a1c76c8910395580cc9cbd11695aa2e3e10e3b2f25afe55e4e4d7"

      def install
        bin.install "templatizer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/wesovilabs/templatizer/releases/download/v0.0.1/templatizer_0.0.1_linux_amd64.tar.gz"
      sha256 "a513a9010015e1dc75c726ceed3141918342a2ac05115cb075c46b028d37b462"

      def install
        bin.install "templatizer"
      end
    end
  end
end
