# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Templatizer < Formula
  desc ""
  homepage "https://github.com/wesovilabs/homebrew-tools"
  version "0.0.1"

  on_macos do
    url "https://github.com/wesovilabs/templatizer/releases/download/v0.0.1/templatizer_0.0.1_darwin_amd64.tar.gz"
    sha256 "f551a645819538d56af3ad8c06e86d574d12de2ca230cd7f022363d4ab6cbb8a"

    def install
      bin.install "templatizer"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Templatizer
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/wesovilabs/templatizer/releases/download/v0.0.1/templatizer_0.0.1_linux_amd64.tar.gz"
      sha256 "448d6ac4cfaaea51b8b8a3ee64f295821ceb56893b9a8e43acb781f7e4db8276"

      def install
        bin.install "templatizer"
      end
    end
  end
end
