# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Templatizer < Formula
  desc ""
  homepage "https://github.com/wesovilabs/homebrew-tools"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wesovilabs/templatizer/releases/download/v0.0.1/templatizer_0.0.1_darwin_amd64.tar.gz"
      sha256 "96b34c108d5e801ef21a94d62baddd47a939603c5cd4b66e286ad0bb75cc4146"

      def install
        bin.install "templatizer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/wesovilabs/templatizer/releases/download/v0.0.1/templatizer_0.0.1_linux_amd64.tar.gz"
      sha256 "4dd8bd19beb7ada6e303a3eaf7349a38471decb02fcfbacadc8de99ff506e74b"

      def install
        bin.install "templatizer"
      end
    end
  end
end
