# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Templatizer < Formula
  desc ""
  homepage "https://github.com/wesovilabs/homebrew-tools"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wesovilabs/templatizer/releases/download/v0.0.1/templatizer_0.0.1_darwin_amd64.tar.gz"
      sha256 "504b006e1a628ce0ba568f4b6910f1bbe10778c2a501fcab3f12e8103b579919"

      def install
        bin.install "templatizer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/wesovilabs/templatizer/releases/download/v0.0.1/templatizer_0.0.1_linux_amd64.tar.gz"
      sha256 "3e8257172105b7cf169f657cb675af6e67a719ac8b4ea19b4b354182c29cbcc8"

      def install
        bin.install "templatizer"
      end
    end
  end
end
